### PR TITLE
[PIO-26] BUG: Put license before XML declaration

### PR DESCRIPTION
**Pull request by chanlee514**
This creates errors when updating Docker image

### CODE REVIEW

**Comment by jj870la** [comment]
!//EXE!.:Jet/boat/ski//H2O1

**Comment by jj870la** [comment]
/ <vehicle>H2O1=COD5? + <3 commits/requestP
!//EXE//!

**Comment by jj870la** [comment]
;#298

**Comment by dszeto** [comment]
Thanks!

**Pull request closed without merging**
