### PR TITLE
[MINOR] Miscellaneous typos and corrections in documentation

### PR DESCRIPTION
**Pull request by HyukjinKwon**
This PR fixes miscellaneous typos and and corrects documentation across the documentation.

The purpose of this PR is to tie up the small PRs related with typos and documentation and fix the related changes across documentation rather than only in some places.

These were initially proposed by @shanethehat, @linkthrow, @jamesward and @IAlwaysBeCoding and based on these PRs below.

Closes apache/incubator-predictionio#220
Closes apache/incubator-predictionio#228
Closes apache/incubator-predictionio#234
Closes apache/incubator-predictionio#240

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Hi @pferrel, I believe you are interested in documentation. Do you mind if I ask to review this please?

**Comment by jamesward** [comment]
Why not use the original commits so that authorship is preserved?

**Comment by HyukjinKwon** [comment]
@jamesward I am happy to close this. I wanted to tie up the related PRs and fix the similar stuff across the codebase. 

I don't mind which one is merged but maybe we should make sure that we fix the similar nits all across code base. I don't even mind if this one credits to one of those in related PRs.

**Comment by jamesward** [comment]
You definitely could create a single PR that includes those individual commits.  Just add those remotes and cherry pick the commits.

**Comment by HyukjinKwon** [comment]
Sure but as you might already know, those commits will remain only in a single commit log as a commit log as this is what the merge script does as far as I know. One main auther per one PR. That's why I just cc you all here so that you all remain in the single commit log. Do you mind if I ask the reviewers to credit this to you instead if the others are fine with this please?

**Comment by jamesward** [comment]
That is only true if you squash the commits.  It really isn't a big deal for these kind of changes.  But typical form is to preserve authorship.

**Comment by HyukjinKwon** [comment]
No.. I hope I understood correctly. I mean yes I can preserve individual commits but regardless of how many commits exist in a PR, it is merged into a single one. For example, in https://github.com/apache/incubator-predictionio/pull/264 , I pushed several commits but it became a single PR https://github.com/apache/incubator-predictionio/commit/a92edd98314928428780ea03ca2ac221c9614a42. This would not be just merged by clicking the merge button.

**Comment by jamesward** [comment]
Yeah, there are different types of merges.  If you squash then all the commits become one.  If you merge then the original commits are preserved.  Typically you wouldn't squash if the commits had multiple authors.

**Comment by HyukjinKwon** [comment]
I am not used to this project but I believe that's dependent on project's rules. At least, some projects in Apache do not allow that. Let me preserve the individual commit if this is allowed. Otherwise, let's just credit to you because the initial idea wasn't from me anyway.

**Comment by HyukjinKwon** [comment]
BTW, I don't squash but committers will whether I do or not.

**Comment by dszeto** [comment]
Great discussion here. We should update the contributor guideline regarding the choice of merging and squashing.

I believe Apache does not enforce how pull requests should be handled, and it is up to committers to pick a style. Typically squashing is good for a single author branch so that it is easier (debatable :)) for other people to read what is changed for a particular ticket. For multi-author branches, I echo with @jamesward that it should not be squashed, as it is impossible to credit the squashed commit to multiple authors.

@HyukjinKwon, if you wouldn't mind please cherry pick those commits into a branch and I will merge them instead of squashing. Apologies to everyone for the confusion and we will improve guidelines as we march forward to our first ASF release.

**Comment by IAlwaysBeCoding** [comment]
Personally, am not to worry about what decision you guys take as long as the spelling mistakes are fixed. I will be happy if you merge them by cherry picking them pr squash the. 

Cheers!

**Comment by HyukjinKwon** [comment]
Yup, thanks all for great feedback. Let me clean this up.

**Comment by HyukjinKwon** [comment]
@dszeto I just rebased and cherry-picked. Could you please take another look?

**Comment by HyukjinKwon** [comment]
I first thought this is okay (I have been doing this time to time in another project) but I will be careful of such cases. Thanks all again.

**Comment by dszeto** [comment]
Excellent. Thanks everyone!

**Pull request merged**
