### PR TITLE
[PIO-116] PySpark Support

### PR DESCRIPTION
**Pull request by marevol**
This PR provides PySpark support with minimum PIO changes.

1. Support pyspark on pio-shell
2. Add python files to use pyspark
3. Add --main-py-file option to "pio train" to submit .py file to spark

Note that this provides only fixes for Spark 2.x.
(because this fixes expect to use SparkML)

Sample project is:
https://github.com/jpioug/predictionio-template-iris
(For prediction API, Scala code is used.)

### CODE REVIEW

**Comment by marevol** [comment]
Thank you for checking it. Replaced with if-else.

**Comment by dszeto** [comment]
@marevol Looks like Python 3 is also a hard requirement? This does not work when I run `pyspark` with Python 2.

**Comment by marevol** [comment]
Added __init__.py. It will work on Python 2.7.

**Comment by dszeto** [comment]
Verified working with Python 2. Thanks!

**Comment by marevol** [comment]
Thanks! I'll merge this PR tomorrow.

**Pull request closed without merging**
