### PR TITLE
[PIO-56] Adding embedded database and mocked configuration for unit tests

### PR DESCRIPTION
**Pull request by lucasbm88**
This pull request will add a code that will avoid the need of an elasticsearch installation and pio-env configuration when running unit tests of the project core.

Basically the changes are:
 - Adding scalamock as a dependency for project core
 - Modifying data Storage.scala file to allow mocked configuration
 - Creating a new helper object to start and shutdown embedded elasticsearch
 - Modifying existing tests to use new infrastructure.

More details of the issue in ASF Jira: https://issues.apache.org/jira/browse/PIO-56

### CODE REVIEW

**Comment by marevol** [comment]
Please see https://github.com/apache/incubator-predictionio/pull/352
We are working on Elasticsearch 5 support.
This fix removes elasticsearch from core.

**Comment by lucasbm88** [comment]
Hi @marevol , thanks for the update

Yes, I noticed that you're removing elasticsearch from core, but correct if I'm wrong, the unit tests in the project core will continue depending on a METADATA configuration in order to run. If it is the case I can update my code to match your changes once you merge it.

**Comment by marevol** [comment]
My concern is core depends on Elasticsearch.
Since Elasticsearch 1.x is EOLed by elastic, it will be removed from PIO in the future release
and PIO will not contain elasticsearch jar in the dependencies(NodeBuilder does not exist).
Others are not changed.

**Comment by lucasbm88** [comment]
Got it, I will wait until you merge your code to update mine.

Thx for the clarification.

**Comment by dszeto** [comment]
@lucasbm88 PIO-49 has been merged. Please take a look. Thanks!

**Comment by lucasbm88** [comment]
Since elasticsearch 1.x should be removed in the near future I updated this PR with a new implementation that uses in-memory H2 (MYSQL mode) to run unit tests. With this code developers can run unit tests on projects core and data without needing to manually setup a metadata or eventdata server.
@dszeto and  @marevol could you review please?

To validate:
 - Clone Prediction-io in a fresh environment
 - Run <pio_src_root>/make-distribution.sh in order to install local pio dependencies.
 - Run <pio_src_root>/sbt core/test
 - Run <pio_src_root>/sbt data/test

None tests should fail. 

Thx

**Comment by brunitto** [comment]
+1

**Comment by browest** [comment]
+1

**Comment by dszeto** [comment]
Sorry for the late reply. LGTM and merging. Thanks @lucasbm88 !

**Pull request closed without merging**
