### PR TITLE
ES 2.x

### PR DESCRIPTION
**Pull request by jramos**
This provides support for Elasticsearch 2.x. It's currently setup to use 2.1.1 (the latest), but any 2.x should work fine.

(I can't get all specs to run locally, so any help testing would be much appreciated. I don't believe there are any failures... I'm just missing a config somewhere. `[Storage$] Required repository (METADATA) configuration is missing.`)

### CODE REVIEW

**Comment by EmergentOrder** [comment]
This compiles, but I get Exception in thread "main" java.lang.NoClassDefFoundError: org/joda/time/base/BaseInterval at runtime. 
replacing the ShadeRule with this one:

ShadeRule.rename("org.joda.time.base.**" -> "shadeio.@1").inLibrary("org.elasticsearch" % "elasticsearch"  % elasticsearchVersion.value).inProject

resolves it. Please make that change, thanks.

**Comment by jramos** [comment]
@EmergentOrder thanks for the fix.

**Comment by pferrel** [comment]
testing indicates a silent failure during training, which is probably because the write to ES using Spark requires an upgrade of the ES-Hadoop lib, from the docs: "ES-Hadoop 2.2.x and higher are compatible with Elasticsearch 1.X and 2.X" See discussion here: https://github.com/elastic/elasticsearch-hadoop

Looks like you can try 2.2.0-rc1https://github.com/elastic/elasticsearch-hadoop#beta-release-currently-220-rc1

**Comment by jramos** [comment]
I didn't think ES-Hadoop was a dependency in PIO. Not seeing it required anywhere...

**Comment by EmergentOrder** [comment]
ES-Hadoop is not a dependency of PIO proper, but rather of Universal Recommendation Template

**Comment by jramos** [comment]
I don't see a dependency in the template. Do you mean the server needs ES-Hadoop installed for UR to work with ES 2.x? Why not with ES 1.x?

**Comment by pferrel** [comment]
in the UR build.sbt 

    "org.elasticsearch" % "elasticsearch-spark_2.10" % "2.1.0.Beta4"
      exclude("org.apache.spark", "spark-catalyst_2.10")
      exclude("org.apache.spark", "spark-sql_2.10"),

The upcoming v0.3.0 uses v 2.1.2. This is a packaging of ES-hadoop that includes only the Spark deps.

**Comment by jramos** [comment]
Ah, got it. Thanks! I'll test out an updated build shortly.

**Comment by pferrel** [comment]
btw we noticed that it seems to be very fast, wonder if you see any speed improvement.

**Comment by jramos** [comment]
Is there any documentation on getting tests to run? I'd like to be able to run the suite, but I get an error (`[Storage$] Required repository (METADATA) configuration is missing.`).

**Comment by k4hoo** [comment]
Try this before run sbt test:

$ set -a
$ source conf/pio-env.sh
$ set +a

there are some development notes in README of https://github.com/PredictionIO/PredictionIO/tree/develop/data . it would be great if you could help update it too if you see anything unclear.

**Comment by jramos** [comment]
Thanks. I just get one failure.

```
[info] EngineSuite:
[info] - Engine.train
[info] - Engine.train persisting PAlgo.Model
[info] - Engine.train persisting LAlgo.Model
[info] - Engine.train persisting P&NAlgo.Model
[info] - Engine.prepareDeploy PAlgo
[info] - Engine.eval *** FAILED ***
[info]   java.lang.IllegalStateException: Cannot call methods on a stopped SparkContext.
[info] This stopped SparkContext was created at:
[info]
[info] org.apache.spark.SparkContext.<init>(SparkContext.scala:147)
[info] io.prediction.workflow.SharedSparkContext$class.beforeAll(BaseTest.scala:65)
[info] io.prediction.controller.EngineSuite.beforeAll(EngineTest.scala:18)
[info] org.scalatest.BeforeAndAfterAll$class.beforeAll(BeforeAndAfterAll.scala:187)
[info] io.prediction.controller.EngineSuite.beforeAll(EngineTest.scala:18)
[info] org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:253)
[info] io.prediction.controller.EngineSuite.run(EngineTest.scala:18)
[info] org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:444)
[info] org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:651)
[info] sbt.TestRunner.runTest$1(TestFramework.scala:76)
[info] sbt.TestRunner.run(TestFramework.scala:85)
[info] sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[info] sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[info] sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
[info] sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[info] sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[info] sbt.TestFunction.apply(TestFramework.scala:207)
[info] sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:239)
[info] sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[info] sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[info]
[info] The currently active SparkContext was created at:
[info]
[info] (No active SparkContext.)
[info]   at org.apache.spark.SparkContext.org$apache$spark$SparkContext$$assertNotStopped(SparkContext.scala:106)
[info]   at org.apache.spark.SparkContext.defaultParallelism(SparkContext.scala:2086)
[info]   at org.apache.spark.SparkContext.parallelize$default$2(SparkContext.scala:728)
[info]   at io.prediction.controller.Engine0$PDataSource2$$anonfun$readEval$2.apply(SampleEngine.scala:69)
[info]   at io.prediction.controller.Engine0$PDataSource2$$anonfun$readEval$2.apply(SampleEngine.scala:65)
[info]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[info]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[info]   at scala.collection.immutable.Range.foreach(Range.scala:141)
[info]   at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
[info]   at scala.collection.AbstractTraversable.map(Traversable.scala:105)
[info]   ...
```

**Comment by jramos** [comment]
@pferrel -- I haven't had a chance to benchmark yet. I'm stuck on an engine registration issue: https://groups.google.com/forum/#!topic/predictionio-user/sVzM6z_eaCY

**Comment by EmergentOrder** [comment]
The test failure you are seeing is unrelated, fixed in PR #199

**Comment by jramos** [comment]
:+1: passing now.

**Comment by jramos** [comment]
I can't tell if my UR engine issue is related to ES 2.x or not. I'm a bit stumped on it. https://groups.google.com/forum/#!topic/predictionio-user/sVzM6z_eaCY

**Comment by voran** [comment]
Any chance this will get merged soon? Any blockers I can help with?

**Comment by jramos** [comment]
I've used it in production for a year now. There aren't any issues I'm aware of.

**Comment by pferrel** [comment]
@voran the reason this hasn't been merged is that ES 2.x libs are not built into Apache PIO. The previous version of ES in the 1.7.x line will need support for some time to come so we need to build for both. That means an sbt option for building 2 artifacts. 

Also ES doesn't like the way sparkConf if used in engine.json so all Spark params must be possible to pass in on the command line. I think this works for all I know of so it means disabling a feature.

@jramos has not updated this PR for Apache PIO so it would need a little work, mostly in changing the PIO namespace to org.apache.predictionio as per the conflicts above. So to use it with Apache PIO you'd need to make those mods.

**Comment by jorelcb** [comment]
@jramos hi, please check possible negative effects on performance about use _queries_ in exchange of
 _filters_ in elasticsearch:

https://www.elastic.co/guide/en/elasticsearch/guide/current/_queries_and_filters.html#_performance_differences

> As a general rule, use query clauses for full-text search or for any condition that should affect the relevance score, and use filters for everything else.

**Comment by marevol** [comment]
@jorelcb To support ES 5.x, we are working on PIO-49. 
https://github.com/apache/incubator-predictionio/pull/195 will be closed.
For query tuning, I'll check it after https://github.com/apache/incubator-predictionio/pull/358 is merged.

**Pull request closed without merging**
