### PR TITLE
[WIP] Events elasticsearch

### PR DESCRIPTION
**Pull request by haginot**

### CODE REVIEW

**Comment by pferrel** [comment]
are you still planning to do this? It might simplify the stack of code required to run PIO for some users.

**Comment by haginot** [comment]
@pferrel I works on this issue. I’ll create a new PR after code-cleanup.

**Comment by pferrel** [comment]
Have you done any benchmarks of performance vs HBase or a database like Postgres?

**Comment by marevol** [comment]
I works with @haginot on this issue.
I'm afraid that our elasticsearch support does not work yet...
So, we will check it when deploying it to our environment.

**Pull request closed without merging**
