### PR TITLE
monit documentation

### PR DESCRIPTION
**Pull request by alex9311**
@dszeto 

[related google group discussion](https://groups.google.com/forum/#!topic/predictionio-user/PoOXqp-aMKk)

Hey Donald, is this what you had in mind? Added it to the deploy section

image is loose in /images/ directory, didn't see a good sub-dir for it

Cheers,
Alex

### CODE REVIEW

**Comment by alex9311** [comment]
@asfgit why was this closed?

**Comment by pferrel** [comment]
Some glitch with moving to the Apache hosted Git, please be patient while we work it out.

**Comment by alex9311** [comment]
Thanks for the quick reply as always, cheers

**Comment by alex9311** [comment]
hey @pferrel  and @dszeto this PR got closed by a glitch, is there anything I can do to get it opened again?

Cheers

**Comment by dszeto** [comment]
@alex9311 Waiting for Apache infrastructure team to reopen them, but I believe it is possible for us to merge your docs even though it's closed. Will keep you posted.

**Comment by dszeto** [comment]
@alex9311 Just want to let you know it is pushed and merged to live documentation. You should be able to see your contribution at http://predictionio.incubator.apache.org. Thanks!

**Comment by alex9311** [comment]
hey @dszeto, thats great! Thanks for getting back to me, cheers

**Pull request closed without merging**
