### PR TITLE
[PIO-63]Add incubator logo and disclaimer to web site

### PR DESCRIPTION
**Pull request by takezoe**
Add an incubator logo and disclaimer to the footer of the web site as follows to resolve an incubator branding issues:

footer

### CODE REVIEW

**Comment by takezoe** [comment]
I put a incubator logo and disclaimer on the footer like Impala (http://impala.incubator.apache.org/) or Hivemail (http://hivemall.incubator.apache.org/), but it might be enough on only the top page like Airflow (https://airflow.incubator.apache.org/). I would like to hear your opinion.

**Comment by shimamoto** [comment]
@dszeto I also would like to hear your opinion.

**Comment by takezoe** [comment]
Merged to `livedoc` branch but the web site hasn't been updated yet.
I'm wondering how is docs deployed on the web site...

**Comment by dszeto** [comment]
@takezoe It's done by our Jenkins project on ASF: https://builds.apache.org/job/PredictionIO-build-site/69/console

Looks like the site built correctly but the publish step failed. I am investigating.

**Comment by takezoe** [comment]
@dszeto I confirmed that my fix has been applied. Thanks for your help!

**Pull request closed without merging**
