### PR TITLE
*Added classification template based on Lingpipe (http://alias-i.com/lingpipe/) algorithm 

### PR DESCRIPTION
**Pull request by haricharan123**
Added one more classification template based on lingpipe

### CODE REVIEW

**Comment by dszeto** [comment]
Thanks @haricharan123 ! Let's merge this when the Apache release is published. There will be name changes to PredictionIO engine artifacts (RE: #292).

**Comment by dszeto** [comment]
@haricharan123 Would you please update your template to use the latest PredictionIO version (0.10.0-incubating)? I'll merge this PR once that's done. Thanks!

**Comment by dszeto** [comment]
@haricharan123 ping

**Comment by haricharan123** [comment]
@dszeto 

sorry, was off work for a while :). Have bumped the version now to 0.10.0-incubating)

**Comment by dszeto** [comment]
Thank you @haricharan123 !

**Pull request closed without merging**
