### PR TITLE
[PIO-34]Update templates.yaml

### PR DESCRIPTION
**Pull request by bansarishah**
Integrate new predictionIO template of sentiment analysis - Bag of words model.

### CODE REVIEW

**Comment by dszeto** [comment]
Hi @bansarishah , thanks for the pull request. Would you mind changing the subject to include the JIRA ticket number so that they are linked? It would be sufficient to just add **`[PIO-34]`** in front of the current subject.

**Comment by bansarishah** [comment]
Hi..
I have changed subject from "Update templates.yaml " to "[PIO-34] Update
templates.yaml"
Please consider it

Thank you

Regards,
Bansari Shah

**Comment by dszeto** [comment]
Thanks for your contribution @bansarishah ! Most of it looks great to me. A few suggested improvement:

* highlight the need to change `appId` in `engine.json`
* or even better, use the `PEventStore` API so that it relies on the app name rather than ID

I will hold this until the Apache release is out. PredictionIO 0.10.0 has reached RC status. Once the final release is published, we will accept this PR after the engine template is modified to use the final released artifact.

**Comment by bansarishah** [comment]
I have updated template with 'PEventStore' API. Now it works on appName instead appId and have mentioned it's use in README.md
Please consider it.
Thank you

**Comment by bansarishah** [comment]
I have done one more commit with addition of new template "Labelling LDA with Wikipedia" in templates.yaml. It relates to Jira Issue [PIO-34] .
Please consider it.
Thank you.

**Comment by dszeto** [comment]
Hi @bansarishah , now that 0.10.0-incubating has released, would you mind updating your template to use those new artifacts? Once that's done I will merge this in.

You might also want to redo this against the `livedoc` branch if you want your entry to show up immediately on the live web site. Thanks!

**Comment by bansarishah** [comment]
Hi @dszeto , I have updated template to use predictionio new release 0.10.0-incubating.
I will redo this against the livedoc branch.
Please consider it.
Thank you

**Comment by dszeto** [comment]
Thank you @bansarishah ! Merging this with livedoc.

**Pull request closed without merging**
