### PR TITLE
PIO-39: All *.md files are missing Apache License Headers

### PR DESCRIPTION
**Pull request by smarthi**

### CODE REVIEW

**Comment by chanlee514** [comment]
I've run RAT license checking after removing .md files from .rat_excludes, and it seems that some files are missing license headers. The results can be seen here: https://travis-ci.org/chanlee514/incubator-predictionio/jobs/166812407

They are obsolete manual docs, so I wanted to check whether I should add license headers or remove the files.

**Comment by smarthi** [comment]
@chanlee514 i saw that those files were in obsolete/ folder, hence I chose to not add headers to them. I suppose they will be purged anyways.

**Comment by chanlee514** [comment]
@smarthi Right okay. It seems like they'll be purged with a seperate PR, and maybe we can remove "*.md" from .rat-excludes following the obsolete/ purge

**Comment by chanlee514** [comment]
Also, on a related note, some .md.erb files are missing license headers, which the RAT check failed to catch due to excluding the "source/" directory path in .rat-excludes. The results are here: https://travis-ci.org/chanlee514/incubator-predictionio/jobs/166822010. I can work on correcting this issue following acceptance of this PR.

**Comment by dszeto** [comment]
I've created https://issues.apache.org/jira/browse/PIO-40. Feel free to pick it up. :)
I'll merge this PR. Thanks!

**Pull request closed without merging**
