### PR TITLE
Fix docs because pio template is no longer supported

### PR DESCRIPTION
**Pull request by takezoe**

### CODE REVIEW

**Comment by tom-chan** [comment]
LGTM, thanks!

**Comment by tom-chan** [comment]
Actually if the PR is made against `livedoc` branch the doc would be updated right away. Do you want to do that instead? Thanks.

**Comment by takezoe** [comment]
@tom-chan Oh, should I make a pull request to fix doc against `livedoc` branch instead of `develop`?

**Comment by dszeto** [comment]
@takezoe Guidelines are here: http://predictionio.incubator.apache.org/community/contribute-documentation/

tl;dr

- Use the livedoc branch if you want to update the current documentation.
- Use the develop branch if you want to write documentation for the next release.

**Comment by takezoe** [comment]
@dszeto Thanks for your advice. I will change the target to `livedoc` branch.

**Comment by takezoe** [comment]
Created new pull request against `livedoc` branch as #379.

**Pull request closed without merging**
